version: '3.8'

services:
  app:
    container_name: spring-app
    image: sonyeoul/spring-app:latest
    ports:
      - "9000:9000"
    env_file:
      - .env  # ✅ .env 파일 자동 로드
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # ✅ Spring Boot 프로파일 설정
    networks:
      - backend_network

networks:
  backend_network: