version: '3.8'

services:
  app:  # ✅ Spring Boot
    container_name: spring-app
    image: sonyeoul/spring-app:latest
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend_network

  ai-server:  # ✅ FastAPI
    container_name: ai-server
    image: sonyeoul/ai-server:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - backend_network

networks:
  backend_network:
