version: '3.8'

services:
  app:
    container_name: spring-app
    image: sonyeoul/spring-app:latest
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGO_DB_URI=${MONGO_DB_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    networks:
      - backend_network

networks:
  backend_network:
