spring:
  profiles:
    active: prod  # prod 프로파일 활성화

  data:
    mongodb:
      uri: ${MONGO_DB_URI}  # GitHub Secrets에서 값을 읽어옴
      database: ${MONGO_DB_NAME}  # GitHub Secrets에서 값을 읽어옴

discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}  # GitHub Secrets에서 값을 읽어옴
server:
  port: 9000  # 운영 환경 포트
