spring:
  data:
    mongodb:
      uri: mongodb+srv://sonyeoul:son10060105@rezoom.r5uns.mongodb.net/Rezoom?retryWrites=true&w=majority&appName=Rezoom  # .env 파일에서 값을 읽어옴
      database: Rezoom # .env 파일에서 값을 읽어옴

discord:
  webhook:
    url: https://discordapp.com/api/webhooks/1351016435547115594/2C2jxDPgHauUYwyN1Fbg-6oM8Qxp1G1nKjEPV79buKXluTopP1iHXmGspMTZIrSY0O_k # .env 파일에서 값을 읽어옴
server:
  port: 8080  # 운영 환경 포트