spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI}  # .env 파일에서 값을 읽어옴
      database: ${MONGO_DB_NAME}  # .env 파일에서 값을 읽어옴
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.181:5432/rezoom
    username: postgres
    password: 1234

    jpa:
      hibernate:
        ddl-auto: update  # 개발 중에는 update, 운영에선 validate or none 권장
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true

springdoc:
  api-docs:
    enabled: true  # Swagger API Docs 활성화
  swagger-ui:
    enabled: true  # Swagger UI 활성화
discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}  # .env 파일에서 값을 읽어옴
server:
  port: 8080  # 운영 환경 포트