spring:
  profiles:
    active: dev  # 기본적으로 개발 환경(dev) 활성화

discord:
  webhook:
    url: ${DISCORD_SPRING}  # GitHub Secrets에서 값을 읽어옴
server:
  port: 8080  # 운영 환경 포트

fastapi:
  base-url: http://localhost:8000  # FastAPI 기본 URL
  endpoint: /process-pdf
