spring:
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
  data:
    mongodb:
      uri: ${MONGO_DB_URI}  # .env 파일에서 값을 읽어옴
      database: ${MONGO_DB_NAME}  # .env 파일에서 값을 읽어옴
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.181:5432/rezoom
    username: postgres
    password: 1234
  jwt:
    secret: 1CUkGbcRHun/pzZ7iX5GLk4AswnEZor6gz1bu9tkfL7bh7x9O40g34qgkdOoct3CyQLh8Rb0nQ5oVKhv2/Ojvw==
  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update, 운영에선 validate or none 권장
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
discord:
  webhook:
    url: ${DISCORD_WEBHOOK_URL}  # .env 파일에서 값을 읽어옴
server:
  max-http-request-header-size: 32KB
  port: 8080  # 운영 환경 포트