name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main  # ✅ main 브랜치에 Push될 때 실행

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ GitHub Repository Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Docker BuildX 설정 (멀티플랫폼 빌드 지원)
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Docker Hub 로그인
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # 4️⃣ Docker 이미지 빌드 & 환경 변수 전달
      - name: Build Docker Image
        run: |
          docker buildx build --platform linux/amd64 \
            --build-arg MONGO_DB_URI=${{ secrets.MONGO_DB_URI }} \
            --build-arg MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }} \
            --build-arg DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }} \
            --build-arg SERVER_PORT=9000 \
            -t sonyeoul/spring-app:latest \
            --push .