name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main  # ✅ main 브랜치에 Push될 때 실행

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ GitHub Repository Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Docker Hub 로그인
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # 3️⃣ Docker 이미지 빌드
      - name: Build Docker Image
        run: |
          docker build -t sonyeoul/spring-app:latest .
          docker tag sonyeoul/spring-app:latest sonyeoul/spring-app:latest

      # 4️⃣ Docker Hub에 Push
      - name: Push Docker Image to Docker Hub
        run: |
          docker push sonyeoul/spring-app:latest